import ToastMessage from "@/components/common/ToastMessage";
import Providers from "@/store/Providers";

export const metadata = {
  title: "Create auth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="h-screen">
      <Providers>
        {" "}
        <ToastMessage />
        {children}
      </Providers>
    </div>
  );
}
