export const metadata = {
  title: "Create auth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <div className="h-screen">{children}</div>;
}
