import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/store/Providers";
import ToastMessage from "@/components/common/ToastMessage";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ToastMessage />
          {children}
        </Providers>
      </body>
    </html>
  );
}
