import ToastMessage from "@/components/common/ToastMessage";
import Providers from "@/store/Providers";

export const metadata = {
  title: "Create admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <ToastMessage />
      {children}
    </Providers>
  );
}
